plugins:
  - rubocop-rubyfmt
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

# There's only really 1-2 classes that will ever be in this project,
# the length on them is irrelevant.
Metrics/ClassLength:
  Enabled: false
